#!/usr/bin/env ruby
require 'optparse'

if ARGV.include?("-h") or (patch_dif = ARGV.shift).nil?
  STDERR.puts "Usage: #{File.basename $0} patch.dif [input] [output]"
  STDERR.puts "  * Input file is patched in-place unless output is specified."
  STDERR.puts "  * If no input file is specified, the file is found in patch.dif."
  exit 1
end

patch_io = File.open(patch_dif)

input = ARGV.shift
output = ARGV.shift

# first line is a comment followed by a blank line
comment = patch_io.readline.chomp

unless blnk = patch_io.readline.chomp.empty?
  STDERR.puts "!!! format error, expected blank line after comment"
  exit 1
end

#next line is the filename to patch according to IDA
fname = patch_io.readline.chomp

input ||= fname
output ||= input

target = File.open(input){|f| f.bytes.to_a }

until patch_io.eof? or (line = patch_io.readline.chomp ) == "%%YAML%%"
  if /^([a-z0-9]+): ([a-z0-9]{2}) ([a-z0-9]{2})/i.match(line)
    off, orig, newval = $~[1..3].map{|x| x.hex }
    target[off] = newval if target[off] == orig
  else
    # ignore
  end
end

File.open(output, "wb"){|f| f.write target.pack("C*") }

